### ISSUE TITLE
Deploy hooks

### ISSUE THREAD

**Issue by thepry** [rubyonjets/jets#131]
## Summary

Would be nice if there was a way to add a hook to `.jets/deploy/hooks.rb` (for Rails mode) or similar and get the executed after the project was copied to `/tmp/jets/turbo-wrapper-project`

## Motivation

This is the easiest way to allow users customise the deploy process. If some files should be removed from public directory or Gemfile needs to be modified before the deploy. (In my case gems take too much space, but some of them can be removed, since they are not going to be used in Lambda)

## Guide-level explanation

- User can add ruby code in `.jets/deploy/hook.rb` that gets executed after the project is copied to tmp directory, but before the rest of deploy happens.

## Reference-level explanation

TBD

## Drawbacks

This feature will be rarely used. 

## Unresolved Questions

TBD

- - - - - 

@tongueroo I can implement this if you support the idea.

**Comment by thepry** [comment]
> Also, wondering if you've considered just removing the gems from Gemfile or only add them to the development group. Jets does not bundle gems in the test or development group. This might help reduce the package size down.

yeah, actually I ended up with writing script that copies project to /tmp/project directory, removes some gems from Gemfile and some files from public folder.

**Comment by tongueroo** [comment]
Deploy hooks are available in Jets 6.0 

* https://docs.rubyonjets.com/docs/hooks/remote/
* https://blog.boltops.com/2024/05/23/ruby-on-jets-6-0-rails-support/
