### ISSUE TITLE
Run sqs_event jobs in local development mode

### ISSUE THREAD

**Issue by douglasjsellers** [rubyonjets/jets#365]
## Summary
When "jets server" is run in local development mode all jobs should be running.  Specifically I would like any jobs based on sqs_event to be running and to respond to events pushed into the queue they are attached to when in local development mode.  Ideally all jobs would work, no matter the type.

## Motivation
Without supporting local jobs doing local development becomes very problematic.  A developer ends up having to continuously deploy any changes to the their jobs any time a modification has been made - this is, obviously, very slow.  It also forces every developer to have an cloudfront stack running in AWS rather than being able to do development locally and then deploy to a common integration environment as is common with many git flows.  

The only alternative to this (that I can find) is to manually run the jobs but even running the manually is a problem as you have fetch the sqs events by hand before executing the jobs.  

## Drawbacks
Ideally this would work consistently for all different types of jobs.  This seems complex and expensive to implement.

**Comment by tongueroo** [comment]
Jets work differently with Jets 6.0  They are essentially Rails ActiveJob jobs. You can use different adapter in development vs production

Related

* https://docs.rubyonjets.com/docs/jobs/enable/
* https://blog.boltops.com/2024/05/23/ruby-on-jets-6-0-rails-support/
* https://learn.boltops.com/curriculums/ruby-on-jets/courses/ruby-on-jets-6-0-guide/lessons/jets-activesupport-rails-serverless-jobs
