### ISSUE TITLE
Deploys unnused gems

### ISSUE THREAD

**Issue by KevinColemanInc** [rubyonjets/jets#406]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |     OSX    |
| Jets             |     2.3.5    |
| Ruby             |    2.5.7     |

---

## Expected Behaviour

When a gem is removed from the Gemfile or Gemfile.lock, it is not deployed.

## Current Behavior

When a gem is removed from the Gemfile or Gemfile.lock, it remains in your gems directory and is still deployed.

## Step-by-step reproduction instructions

1. Add a very large gem to your Gemfile (like `bootstrap-sass`)
2. bundle install
3. Deploy the app
4. Remove the gem from your Gemfile
5. bundle install
6. Deploy the app
7. Notice how the the gems directory (`open /tmp/jets/{project_name}/stage/code/vendor/gems/ruby/2.5.0/`) still has the gem inside it.
8. If your lambda package is too large, then it rejects the deploy.

## Solution Suggestion

1. Quick and easy: Offer a "clean" command to clear out the cache
2. If your Gemfile.lock file changes since the last deploy, clean the gem cache
3. Only remove the gems that are not inside your Gemfile.lock

**Comment by tongueroo** [comment]
Jets 6.0 uses Docker to build dependencies upon deployment. It's customizable.

* https://blog.boltops.com/2024/05/23/ruby-on-jets-6-0-rails-support/
* https://docs.rubyonjets.com/docs/docker/dockerfile/packages/
