### ISSUE TITLE
`console` support for Jets::Turbine for running pry console

### ISSUE THREAD

**Issue by dosuken123** [rubyonjets/jets#411]
## Summary

I was checking if I use pry console for debugging. It seems there are no gems like pry-rails. I assume this is because  `Jets::Turbine` currently doesn't support `console` option. See https://github.com/rweng/pry-rails/blob/master/lib/pry-rails/railtie.rb how an external gem can extend the behavior.

## Motivation

For debugging

**Comment by sereneiconoclast** [comment]
FWIW, on my system, if I alter `lib/ruby/gems/2.7.0/gems/jets-2.3.16/lib/jets/commands/console.rb` to change this:

```
require "irb"
require "irb/completion"
IRB.start
```

...to this:

```
require "pry"
Pry.start
```

...that's sufficient to make `jets console` bring up Pry.

I've also added `gem 'pry'` and `gem 'pry-byebug'` to my `Gemfile` in the `group :development, :test` section. `pry-byebug` is optional but it's nice, synergizing with `byebug` which is already there. Placing a breakpoint can be done by adding `binding.pry` in the code, giving you both Pry and Byebug commands.

**Comment by jeremiahlukus** [comment]
@tongueroo  this can be closed i use pry works fine now.

**Comment by djolereject** [comment]
> @tongueroo this can be closed i use pry works fine now.

Please tell us how, because I cannot make it work with Jets 5.0.
