### ISSUE TITLE
Fresh project install getting InvalidClientTokenId when trying to run locally

### ISSUE THREAD

**Issue by bruno-trindade** [rubyonjets/jets#498]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |   OS X 10.15.5      |
| Jets             |    2.3.16     |
| Ruby             |    2.7.0     |

---

## Expected Behaviour

Given I cd into the folder of a newly created project and run `jets server`
Then the server should be up and running on `localhost:8888`

## Current Behavior

When I cd into the folder and run `jets server`, I get the following error and the app is not run:

```
Traceback (most recent call last):
	20: from /Users/bruno/.rvm/gems/ruby-2.7.0/bin/jets:23:in `<main>'
	19: from /Users/bruno/.rvm/gems/ruby-2.7.0/bin/jets:23:in `load'
	18: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/jets-2.3.16/exe/jets:14:in `<top (required)>'
	17: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/jets-2.3.16/lib/jets/cli.rb:5:in `start'
	16: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/jets-2.3.16/lib/jets/cli.rb:25:in `start'
	15: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/jets-2.3.16/lib/jets/cli.rb:46:in `boot_jets'
	14: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/jets-2.3.16/lib/jets/core.rb:18:in `boot'
	13: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/jets-2.3.16/lib/jets/booter.rb:21:in `boot!'
	12: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/jets-2.3.16/lib/jets/application.rb:24:in `configs!'
	11: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/jets-2.3.16/lib/jets/application.rb:178:in `set_iam_policy'
	10: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/jets-2.3.16/lib/jets/application/defaults.rb:11:in `default_iam_policy'
	 9: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/memoist-0.16.2/lib/memoist.rb:169:in `account'
	 8: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/jets-2.3.16/lib/jets/aws_info.rb:57:in `account'
	 7: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/aws-sdk-core-3.101.0/lib/aws-sdk-sts/client.rb:1698:in `get_caller_identity'
	 6: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/aws-sdk-core-3.101.0/lib/seahorse/client/request.rb:72:in `send_request'
	 5: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/aws-sdk-core-3.101.0/lib/seahorse/client/plugins/response_target.rb:25:in `call'
	 4: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/aws-sdk-core-3.101.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
	 3: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/aws-sdk-core-3.101.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
	 2: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/aws-sdk-core-3.101.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
	 1: from /Users/bruno/.rvm/gems/ruby-2.7.0/gems/aws-sdk-core-3.101.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
/Users/bruno/.rvm/gems/ruby-2.7.0/gems/aws-sdk-core-3.101.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': The security token included in the request is invalid. (Aws::STS::Errors::InvalidClientTokenId)
```

## Step-by-step reproduction instructions

Create a brand new project with:
```
$ jets new serverless-example --mode api --database=postgresql
```

Change into the new folder `serverless-example` and run
```
$ jets server
```

Observe the error, and the server does not run.

**Comment by bruno-trindade** [comment]
This was fixed by adding the correct access key in `~/.aws/credentials`.

**Comment by timlawrenz** [comment]
@bruno-trindade given your comment regarding access key, should this ticket be closed?

**Comment by derigible** [comment]
I also had this issue when I started my first project with Jets today, and I worked around the issue by adding the following line in `.env.development`:

`JETS_AWS_ACCOUNT=xx`

This will make Jets treat your aws like it is a local account. I am not sure if it will have other issues yet, but it at least got the server started for me.

**Comment by ssunday** [comment]
> I also had this issue when I started my first project with Jets today, and I worked around the issue by adding the following line in `.env.development`:
> 
> `JETS_AWS_ACCOUNT=xx`
> 
> This will make Jets treat your aws like it is a local account. I am not sure if it will have other issues yet, but it at least got the server started for me.

This worked for me.

**Comment by ssunday** [comment]
In test env it just returns a fake account number https://github.com/boltops-tools/jets/blob/master/lib/jets/aws_info.rb#L51 

And it'll use `JETS_AWS_ACCOUNT` if supplied. Maybe this should be documented about local development w/o having to have a live AWS account in use?
