### ISSUE TITLE
Jets 3.0.17 significant increase in Lambda duration

### ISSUE THREAD

**Issue by tlhampton13** [rubyonjets/jets#597]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |    deployed to AWS     |
| Jets             |     3.0.17    |
| Ruby             |    2.7.2     |

---

## Expected Behaviour
After upgrading Jets from 3.0.13 to 3.0.17, we noticed Lambda durations increase significantly for all endpoints in our REST API.

## Current Behavior

After upgrading Jets from 3.0.13 to 3.0.17, lambda durations should be similar to before deployment. Lambda cost for our system increased 8 fold after the upgrade.

## Step-by-step reproduction instructions

* observe avg lambda duration
* upgrade Jets from 3.0.13 to 3.0.17
* deploy to AWS
* observe avg lambda duration
* note significant increase in avg duration for all lambdas

## Code Sample

Duration of all lambdas in our system increased significantly ... even when no code changes were made, other than the Jets upgrade.

## Solution Suggestion

Fix performance issue.

**Comment by tongueroo** [comment]
Thinking Jets 5 handles this since there’s only one Lambda function for all controllers.  

https://blog.boltops.com/2023/12/05/jets-5-improvements-galore/
