### ISSUE TITLE
Deploy application code to a Lambda layer instead of to the Function

### ISSUE THREAD

**Issue by tlhampton13** [rubyonjets/jets#606]
## Summary

Deploy application code as a layer instead of directly to the lambdas. Each lambda is currently deployed with a separate copy of the entire application code. Creating a code-layer will significantly reduce the amount of Lambda Code Storage used by Jets. All that should need to be deployed to the lambdas is a proxy function to the code stored in the layer.

## Motivation

We have hit the Lambda Code Storage limit multiple times. Deploying all application code to every lambda consumes a lot of Lambda Code Storage.

**Comment by tongueroo** [comment]
Jets 5 handles this in another way. A single lambda function is deployed to handle all controller requests. 

https://blog.boltops.com/2023/12/05/jets-5-improvements-galore/

Closing out
