### ISSUE TITLE
ActiveRecord doesnt load multiple connection

### ISSUE THREAD

**Issue by andersonxrilo** [rubyonjets/jets#609]
Hi, I was trying to work with multiple bases within the project. ActiveRecord supports this through connection pools. I'm having the problem when I try to load a secondary connection. When Jets loads the first time, it calls the settings of all connections correctly, however, when I call the Specific Model jets returns failure in the connection pool. When I do a puts to the queue after calling the model, it returns as if I had erased everything that isn't ActiveRecord::Base

## Checklist

- [ ] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [ ] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.rubyonjets.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |         |
| Jets             |         |
| Ruby             |         |

---

**Comment by tongueroo** [comment]
Would like to see an demo project example 🙏 Closing out to clean up issues. Feel free to reopen with a provide example to reproduce.
