### ISSUE TITLE
Routes Helper Methods do not generate

### ISSUE THREAD

**Issue by arturjaworski-htd** [rubyonjets/jets#622]
## Checklist

- [x] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [x] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [x] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |  macOS 12.2.1 |
| Jets             | 3.1.1 |
| Ruby             | 2.7.5p203 |

---

## Expected Behaviour
Following the [Routing Guide](https://rubyonjets.com/docs/routing/guide/) it should generate helper methods.

## Current Behavior
After executing the command `bundle exec jets routes` it gets this result:

<img width="505" alt="image" src="https://user-images.githubusercontent.com/82937084/159961871-d1621f28-16b7-4767-ad54-95450e7da91f.png">
The behavior is the same with different settings, I would like to use helper methods in rspec tests.

## Code Sample
`config/routes.rb`:

```
Jets.application.routes.draw do
  resources :users, only: [] do
    collection do
      get :me
      put :update, to: "users#update", as: :update
      post :update_avatar
      post :remove_avatar
    end
  end
end
```

**Comment by jeremiahlukus** [comment]
@tongueroo  this is something that I have came across as well, url helpers are only generated for GET requests 

```
    get "profile", to: "registrations#edit", as: :profile
    patch "profile", to: "registrations#update", as: :update_profile
    delete "profile", to: "registrations#delete", as: :delete_user
    ```
    
<img width="849" alt="Screenshot 2023-09-13 at 10 37 54 PM" src="https://github.com/boltops-tools/jets/assets/17206638/4d940323-0514-44be-83b4-5acd129cde7f">


Does this happen on v5? If so ill pick this one up.

**Comment by tongueroo** [comment]
On v5 they are generated for all CRUD methods. So v5 will close this.

**Comment by tongueroo** [comment]
Fixed in v5
