### ISSUE TITLE
Localstack Support

### ISSUE THREAD

**Issue by SteffanPerry** [rubyonjets/jets#625]
We use Jet's for much of our application, Until now we have worked with the API locally using `jets server` but when building jobs, we have relied on mostly unit test. I am considering using my 20% time at work to begin the process of adding localstack to jets beginning with what is probably our most used lambda triggers (SNS/SQS/DynamoDb Stream). 

Looking to get some feedback about this. 

## Motivation

To get a fully working local jets environment.

## Unresolved Questions

1: In the ruby world, its very common to be using Rails with Sidekiq. Generally you start the rails server and sidekiq independently. ie `rails s` & `sidekiq`, I wondering if we should do the same `jets server` & `jets jobs` (bad name)?

**Comment by jeremiahlukus** [comment]
Having worked with serverless applications for a long time I think the best way is to deploy a test env run your tests the tear it down. We do this at my work for 50+ serverless apps since mocking all of aws services quickly becomes unmanageable.

**Comment by tongueroo** [comment]
Jets 6 handles the job / worker tier with an ActiveJob adapter. Can just use a different adapter in local development.rb now

Related:

* https://blog.boltops.com/2024/05/23/ruby-on-jets-6-0-rails-support/
* https://learn.boltops.com/curriculums/ruby-on-jets/courses/ruby-on-jets-6-0-guide/lessons/jets-activesupport-rails-serverless-jobs
* https://docs.rubyonjets.com/docs/jobs/enable/
