### ISSUE TITLE
PATCH in form being translated to POST in api gateway

### ISSUE THREAD

**Issue by jeremiahlukus** [rubyonjets/jets#673]
## Checklist

- [ X] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [X ] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [ ] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |         |
| Jets             |    4.0.2     |
| Ruby             |    3.2     |

---

## Current Behavior
Using a namespaced route 

```
  namespace :admin do
    patch "users", to: "users#update", as: :admin_users
  end 
```
Then a form 

```
 <%= form_with model: @user, local: true, url: admin_users_path do |form| %>
 ...
 ```
 
 This works locally however when deployed the on submit turns into a POST request.
 
 changing my route to a POST and adding `method: :post` to the form fixed the issue for me. 
Im not sure what is causing this since its only when deployed. Ill look further into it and see if I can find out where this is happening and send a PR unless this is fixed in v5. 

I do have a custom domain setup that might be causing the issue as well (?). Ill create a test repo with an example if this isn't fixed in v5.

**Comment by tongueroo** [comment]
Fixed in v5
