### ISSUE TITLE
Deploying 5.0.0

### ISSUE THREAD

**Issue by djolereject** [rubyonjets/jets#681]
## Checklist

- [X] Upgrade Jets: Are you using the latest version of Jets? This allows Jets to fix issues fast. There's a `jets upgrade` command that makes this a simple task. There's also an Upgrading Guide: http://rubyonjets.com/docs/upgrading/
- [X] Reproducibility: Are you reporting a bug others will be able to reproduce and not asking a question. If you're unsure or want to ask a question, do so on https://community.boltops.com
- [X] Code sample: Have you put together a code sample to reproduce the issue and make it available?  Code samples help speed up fixes dramatically. If it's an easily reproducible issue, then code samples are not needed. If you're unsure, please include a code sample.

## My Environment

| Software         | Version |
| ---------------- | ------- |
| Operating System |    MacOS     |
| Jets             |     5.0.0    |
| Ruby             |    3.2.0     |

---

## Expected Behaviour

When I run `jets deploy`, it should deploy without any issues.

## Current Behavior
I get error right after bundling of gems is done. Here is the backtrace:

<details>
 <summary>jets deploy backtrace</summary>

	Tidying project: removing ignored files to reduce package size.
	=> rsync -a --links /tmp/jets/scraper/stage/code/vendor/gems/ruby/3.2.0/ /tmp/jets/scraper/stage/opt/ruby/gems/3.2.0/
	=> Replacing compiled gems with AWS Lambda Linux compiled versions: /tmp/jets/scraper/stage/opt
	Checking project for compiled gems...
	/Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/turbine/configuration.rb:96:in `method_missing': undefined method `assets' for #<Jets::Application::Configuration:0x000000010ac99388 @root=#<Pathname:/Users/djole/work/pugbite/scraping/scraper>, @generators=#<Jets::Configuration::Generators:0x000000010a1dc6c0 @aliases={}, @options={}, @fallbacks={}, @templates=[], @colorize_logging=true, @api_only=false, @hidden_namespaces=[], @after_generate_callbacks=[]>, @middleware=#<ActionDispatch::MiddlewareStack:0x000000010951f928 @middlewares=[ActionDispatch::Static, Rack::Sendfile, ActionDispatch::Executor, ActionDispatch::ServerTiming, ActiveSupport::Cache::Strategy::LocalCache::Middleware, Rack::Runtime, Rack::MethodOverride, ActionDispatch::RequestId, ActionDispatch::RemoteIp, Jets::Rack::Logger, ActionDispatch::ShowExceptions, ActionDispatch::DebugExceptions, ActionDispatch::Reloader, Jets::Controller::Middleware::Mimic, ActionDispatch::Callbacks, ActionDispatch::Cookies, ActionDispatch::Session::CookieStore, ActionDispatch::Flash, ActionDispatch::ContentSecurityPolicy::Middleware, ActionDispatch::PermissionsPolicy::Middleware, Rack::Head, Rack::ConditionalGet, Rack::ETag, Rack::TempfileReaper]>, @javascript_path="javascript", @api=#<ActiveSupport::OrderedOptions {:api_key_required=>false, :authorization_type=>"NONE", :authorizers=>#<ActiveSupport::OrderedOptions {:default_token_source=>"Auth"}>, :auto_replace=>nil, :binary_media_types=>["multipart/form-data"], :cors=>false, :endpoint_policy=>nil, :endpoint_type=>"EDGE", :vpc_endpoint_ids=>nil}>, @api_mode=nil, @app=#<ActiveSupport::OrderedOptions {:domain=>nil}>, @build=#<ActiveSupport::OrderedOptions {:prebundle_copy=>[]}>, @cfn=#<ActiveSupport::OrderedOptions {:build=>#<ActiveSupport::OrderedOptions {:controllers=>"one_lambda_for_all_controllers", :resource_tags=>{}, :routes=>"one_apigw_method_for_all_routes"}>}>, @controllers=#<ActiveSupport::OrderedOptions {:default_protect_from_forgery=>nil}>, @deploy=#<ActiveSupport::OrderedOptions {:stagger=>#<ActiveSupport::OrderedOptions {:enabled=>false, :batch_size=>10}>}>, @domain=#<ActiveSupport::OrderedOptions {:base_path=>"", :endpoint_type=>"REGIONAL", :route53=>true}>, @environment=#<ActiveSupport::OrderedOptions {}>, @events=#<ActiveSupport::OrderedOptions {:dynamodb=>#<ActiveSupport::OrderedOptions {:table_namespace=>true, :table_namespace_separator=>"_"}>, :s3=>#<ActiveSupport::OrderedOptions {:configure_bucket=>true, :notification_configuration=>{:topic_configurations=>[{:events=>["s3:ObjectCreated:*"], :topic_arn=>"!Ref SnsTopic"}]}}>}>, @s3_event=#<ActiveSupport::OrderedOptions {}>, @filter_parameters=[], @function=#<ActiveSupport::OrderedOptions {:ephemeral_storage=>{:size=>512}, :memory_size=>1536, :timeout=>30}>, @gems=#<ActiveSupport::OrderedOptions {:clean=>false, :disable=>false, :source=>"https://api.serverlessgems.com/api/v1"}>, @pro=#<ActiveSupport::OrderedOptions {:disable=>false}>, @helpers=#<ActiveSupport::OrderedOptions {:host=>nil}>, @helpers_paths=["/Users/djole/work/pugbite/scraping/scraper/app/helpers"], @inflections=#<ActiveSupport::OrderedOptions {:irregular=>{}}>, @lambda=#<ActiveSupport::OrderedOptions {:layers=>[]}>, @logger=#<ActiveSupport::Logger:0x000000010b39a470 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x000000010a7d9e88 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x000000010a7d94b0 @datetime_format=nil>, @logdev=#<Logger::LogDevice:0x000000010b39a420 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @binmode=false, @mon_data=#<Monitor:0x000000010a7d9848>, @mon_data_owner_object_id=9460>>, @logging=#<ActiveSupport::OrderedOptions {:event=>false}>, @mode="html", @prewarm=#<ActiveSupport::OrderedOptions {:enable=>true, :public_ratio=>3, :rate=>"30 minutes"}>, @routes=#<ActiveSupport::OrderedOptions {:allow_sibling_conflicts=>true}>, @default_iam_policy=[{:Action=>["logs:*"], :Effect=>"Allow", :Resource=>"arn:aws:logs:eu-central-1:228342851134:log-group:/aws/lambda/scraper-dev-*"}, {:Action=>["s3:Get*", "s3:List*", "s3:HeadBucket"], :Effect=>"Allow", :Resource=>"arn:aws:s3:::scraper-dev-s3bucket-5im0n0e7mf0b*"}, {:Action=>["cloudformation:DescribeStacks", "cloudformation:DescribeStackResources"], :Effect=>"Allow", :Resource=>"arn:aws:cloudformation:eu-central-1:228342851134:stack/scraper-dev*"}], @managed_policy_definitions=[], @managed_iam_policy=["AWSLambda_FullAccess"], @encoding=#<Encoding:UTF-8>, @allow_concurrency=nil, @consider_all_requests_local=true, @filter_redirect=[], @hosts=[".localhost", #<IPAddr: IPv4:0.0.0.0/0.0.0.0>, #<IPAddr: IPv6:0000:0000:0000:0000:0000:0000:0000:0000/0000:0000:0000:0000:0000:0000:0000:0000>], @host_authorization={}, @public_file_server=#<ActiveSupport::OrderedOptions {:enabled=>true, :index_name=>"index"}>, @force_ssl=false, @ssl_options={}, @session_store=:cookie_store, @time_zone="UTC", @beginning_of_week=:monday, @log_level=:debug, @cache_store=:null_store, @turbines_order=[:all], @relative_url_root=nil, @reload_classes_only_on_change=true, @file_watcher=ActiveSupport::FileUpdateChecker, @exceptions_app=nil, @autoflush_log=true, @log_formatter=#<ActiveSupport::Logger::SimpleFormatter:0x000000010b979a08 @datetime_format=nil>, @eager_load=false, @secret_key_base=nil, @api_only=false, @debug_exception_response_format=nil, @x=#<Jets::Application::Configuration::Custom:0x000000010b979990 @configurations={}>, @enable_dependency_loading=false, @read_encrypted_secrets=false, @content_security_policy=nil, @content_security_policy_report_only=false, @content_security_policy_nonce_generator=nil, @content_security_policy_nonce_directives=nil, @require_master_key=false, @loaded_config_version=nil, @credentials=#<ActiveSupport::OrderedOptions {:content_path=>#<Pathname:/Users/djole/work/pugbite/scraping/scraper/config/credentials.yml.enc>, :key_path=>#<Pathname:/Users/djole/work/pugbite/scraping/scraper/config/master.key>}>, @disable_sandbox=false, @add_autoload_paths_to_load_path=true, @permissions_policy=nil, @rake_eager_load=false, @server_timing=true, @paths=#<Jets::Paths::Root:0x000000010b95fc48 @path=#<Pathname:/Users/djole/work/pugbite/scraping/scraper>, @root={"app"=>#<Jets::Paths::Path:0x000000010b3b1b98 @paths=["app"], @current="app", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob="{*,*/concerns}", @exclude=["assets", "javascript"], @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/assets"=>#<Jets::Paths::Path:0x000000010b3b1af8 @paths=["app/assets"], @current="app/assets", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "app/controllers"=>#<Jets::Paths::Path:0x000000010b3b1a58 @paths=["app/controllers"], @current="app/controllers", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/channels"=>#<Jets::Paths::Path:0x000000010b3b19b8 @paths=["app/channels"], @current="app/channels", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/helpers"=>#<Jets::Paths::Path:0x000000010b3b1918 @paths=["app/helpers"], @current="app/helpers", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/models"=>#<Jets::Paths::Path:0x000000010b3b1878 @paths=["app/models"], @current="app/models", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/mailers"=>#<Jets::Paths::Path:0x000000010b3b17d8 @paths=["app/mailers"], @current="app/mailers", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=true, @autoload=false, @load_path=false>, "app/views"=>#<Jets::Paths::Path:0x000000010b3b1738 @paths=["app/views"], @current="app/views", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "app/functions"=>#<Jets::Paths::Path:0x000000010b3b1698 @paths=["app/functions"], @current="app/functions", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "app/shared"=>#<Jets::Paths::Path:0x000000010b3b15f8 @paths=["app/shared"], @current="app/shared", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "app/shared/extensions"=>#<Jets::Paths::Path:0x000000010b3b1558 @paths=["app/shared/extensions"], @current="app/shared/extensions", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "app/shared/functions"=>#<Jets::Paths::Path:0x000000010b3b14b8 @paths=["app/shared/functions"], @current="app/shared/functions", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "app/shared/resources"=>#<Jets::Paths::Path:0x000000010b3b1418 @paths=["app/shared/resources"], @current="app/shared/resources", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib"=>#<Jets::Paths::Path:0x000000010b3b1378 @paths=["lib"], @current="lib", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "lib/assets"=>#<Jets::Paths::Path:0x000000010b3b12d8 @paths=["lib/assets"], @current="lib/assets", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/tasks"=>#<Jets::Paths::Path:0x000000010b3b1238 @paths=["lib/tasks"], @current="lib/tasks", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob="**/*.rake", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config"=>#<Jets::Paths::Path:0x000000010b3b1198 @paths=["config"], @current="config", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environments"=>#<Jets::Paths::Path:0x000000010b3b10f8 @paths=["config/environments"], @current="config/environments", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob="development.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/initializers"=>#<Jets::Paths::Path:0x000000010b3b1058 @paths=["config/initializers"], @current="config/initializers", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/locales"=>#<Jets::Paths::Path:0x000000010b3b0fb8 @paths=["config/locales"], @current="config/locales", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob="**/*.{rb,yml}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes.rb"=>#<Jets::Paths::Path:0x000000010b3b0f18 @paths=["config/routes.rb"], @current="config/routes.rb", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/routes"=>#<Jets::Paths::Path:0x000000010b3b0e78 @paths=["config/routes"], @current="config/routes", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob="**/*.rb", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db"=>#<Jets::Paths::Path:0x000000010b3b0dd8 @paths=["db"], @current="db", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/migrate"=>#<Jets::Paths::Path:0x000000010b3b0d38 @paths=["db/migrate"], @current="db/migrate", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "db/seeds.rb"=>#<Jets::Paths::Path:0x000000010b3b0c98 @paths=["db/seeds.rb"], @current="db/seeds.rb", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "vendor"=>#<Jets::Paths::Path:0x000000010b3b0bf8 @paths=["vendor"], @current="vendor", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=true>, "vendor/assets"=>#<Jets::Paths::Path:0x000000010b3b0b58 @paths=["vendor/assets"], @current="vendor/assets", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob="*", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/database"=>#<Jets::Paths::Path:0x000000010b3b0ab8 @paths=["config/database.yml"], @current="config/database", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/secrets"=>#<Jets::Paths::Path:0x000000010b3b0a18 @paths=["config"], @current="config/secrets", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob="secrets.yml{,.enc}", @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "config/environment"=>#<Jets::Paths::Path:0x000000010b3b0978 @paths=["config/environment.rb"], @current="config/environment", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "lib/templates"=>#<Jets::Paths::Path:0x000000010b3b08d8 @paths=["lib/templates"], @current="lib/templates", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "log"=>#<Jets::Paths::Path:0x000000010b3b0838 @paths=["log/development.log"], @current="log", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public"=>#<Jets::Paths::Path:0x000000010b3b0798 @paths=["public"], @current="public", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/javascripts"=>#<Jets::Paths::Path:0x000000010b3b06f8 @paths=["public/javascripts"], @current="public/javascripts", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "public/stylesheets"=>#<Jets::Paths::Path:0x000000010b3b0658 @paths=["public/stylesheets"], @current="public/stylesheets", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>, "tmp"=>#<Jets::Paths::Path:0x000000010b3b05b8 @paths=["tmp"], @current="tmp", @root=#<Jets::Paths::Root:0x000000010b95fc48 ...>, @glob=nil, @exclude=nil, @autoload_once=false, @eager_load=false, @autoload=false, @load_path=false>}>, @autoload_paths=[], @eager_load_paths=["/Users/djole/work/pugbite/scraping/scraper/app/controllers", "/Users/djole/work/pugbite/scraping/scraper/app/helpers", "/Users/djole/work/pugbite/scraping/scraper/app/jobs", "/Users/djole/work/pugbite/scraping/scraper/app/models", "/Users/djole/work/pugbite/scraping/scraper/app/services"], @autoload_once_paths=[], @webpacker=#<ActiveSupport::OrderedOptions {}>, @session_options={:key=>"_main_session", :cookie_only=>true}> (NoMethodError)
	Did you mean?  asset_host
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/builders/code_builder.rb:149:in `s3_base_url'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/builders/code_builder.rb:139:in `write_s3_base_url'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/builders/code_builder.rb:134:in `store_s3_base_url'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/builders/code_builder.rb:96:in `code_finish'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/builders/code_builder.rb:41:in `block in build'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/builders/code_builder.rb:37:in `chdir'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/builders/code_builder.rb:37:in `build'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/commands/deploy/deploy_command.rb:29:in `perform'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/command/base.rb:101:in `perform'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/command.rb:48:in `invoke'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/commands.rb:17:in `<top (required)>'
		from <internal:/Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
		from <internal:/Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/core_ext/kernel.rb:11:in `require'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/cli.rb:16:in `<top (required)>'
		from <internal:/Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
		from <internal:/Users/djole/.rbenv/versions/3.2.0/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/lib/jets/core_ext/kernel.rb:11:in `require'
		from /Users/djole/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/jets-5.0.0/exe/jets:5:in `<top (required)>'
		from /Users/djole/.rbenv/versions/3.2.0/bin/jets:25:in `load'
		from /Users/djole/.rbenv/versions/3.2.0/bin/jets:25:in `<main>'
</details>

I have no idea what could cause this. I upgraded with `jets-upgrade go` and it looks like it works locally but deployment is always crashing.

Thanks!

**Comment by djolereject** [comment]
I'll get back to you with the answer if adding sprockets-jets to Gemfile resolvs an issue, but here is the Gemfile of fresh project:

```
source "https://rubygems.org"

gem "jets", "~> 5.0.0"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"
gem "sprockets-jets"
gem "importmap-jets"
gem "zeitwerk", ">= 2.6.12"

# development and test groups are not bundled as part of the deployment
group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rack'
  gem 'puma'
end

group :test do
  gem 'rspec'
end
```

**Comment by djolereject** [comment]
Yeah, it's working now. Thanks!

**Comment by tongueroo** [comment]
Great to hear. 

Wondering if should make some changes to allow it to work without sprockets-jets. Will have to let it simmer on the brain. 🤔 Closing this out.

**Comment by tongueroo** [comment]
In #686 made sprockets-jets optional
